### ISSUE TITLE
ExifReader Could not find resource

### ISSUE THREAD

**Issue by cblanos** [lorinbeer/cordova-exif-utility#7] opened 2013-05-08 04:38 UTC
``` javascript
ExifReader.getExifData(fileURI, EXIFsuccess, EXIFfail); 
```

Results in error **ExifReader Could not find resource** when passed a fileURI which contains EXIF data.

iOS | PhoneGap 2.7 | XCode 4.6.2 | 6.1 Simulator

**Comment by lorinbeer** [comment] 2013-05-08 22:58
some extra detail from @cblanos 
"""
Sorry to be a pain, but I've been trying to get the EXIF data from camera roll images, and still hit the same issues as before. I'm now running PhoneGap 2.7, with XCode 4.6.2, 6.1 Simulator.

I'm using the same cordova-imagemetadata-plugin as before that I grabbed from GitHub here (is this correct? - files haven't been updated for a month): 
https://github.com/lorinbeer/cordova-imagemetadata-plugin/tree/master/iOS

I'm retrieving the image from the camera roll like this:
    navigator.camera.getPicture( photoSelected, onFail, {
        quality: 100,
        destinationType: Camera.DestinationType.FILE_URI,
        sourceType: Camera.PictureSourceType.PHOTOLIBRARY
    } );

Once I have the fileURI, I attempt to grab the Exif data like this:
ExifReader.getExifData(fileURI, EXIFsuccess, EXIFfail);

But get the same error as I did previously:

2013-05-07 23:24:50.334 GeoStamp[20665:c07] {
    ColorModel = RGB;
    Depth = 8;
    PixelHeight = 956;
    PixelWidth = 1280;
    "{JFIF}" =     {
        DensityUnit = 0;
        JFIFVersion =         (
            1,
            1
        );
        XDensity = 1;
        YDensity = 1;
    };
}
"""

**Comment by lorinbeer** [comment] 2013-05-08 23:11
Got a chance to look at this, and everything is working as it should be. Here is the metadata returned by the plugin:

2013-05-08 16:07:51.143 EXIFTEST[278:907] {
    ColorModel = RGB;
    Depth = 8;
    Orientation = 1;
    PixelHeight = 640;
    PixelWidth = 640;
    "{Exif}" =     {
        ApertureValue = "2.526069";
        BrightnessValue = "2.440841";
        ColorSpace = 1;
        DateTimeDigitized = "2013:05:08 16:07:49";
        DateTimeOriginal = "2013:05:08 16:07:49";
        ExposureMode = 0;
        ExposureProgram = 2;
        ExposureTime = "0.05";
        FNumber = "2.4";
        Flash = 24;
        FocalLenIn35mmFilm = 33;
        FocalLength = "4.13";
        ISOSpeedRatings =         (
            64
        );
        MeteringMode = 5;
        PixelXDimension = 640;
        PixelYDimension = 640;
        SensingMethod = 2;
        ShutterSpeedValue = "4.321957";
        SubjectArea =         (
            1631,
            1223,
            881,
            881
        );
        WhiteBalance = 0;
    };
    "{JFIF}" =     {
        DensityUnit = 0;
        JFIFVersion =         (
            1,
            1
        );
        XDensity = 1;
        YDensity = 1;
    };
    "{TIFF}" =     {
        Orientation = 1;
    };
}

Currently GEO data is not supported, but we have the code to do it, just needs a quick cleanup and push to the repo. I think your problem may have to do with how you are using the plugin, which is in an intelligent way, and how I'm returning the data from the plugin, which is in a stupid way.

May I see your EXIFSuccess and EXIFFail functions?
- Lorin

**Comment by lorinbeer** [comment] 2013-05-09 00:04
Identified the problem: this falls under a bug in Cordova 2.7.0, not in this plugin.

Use the current development head of Cordova for the fix to this issue, exif for camera roll images was not supported in 2.7.0 due to how Cordova handled comera roll images. 

Using the plugin and the head of Cordova-ios, I was able to get the results posted above.

Closing: reproducible but not a bug in the plugin

**Closed as completed by lorinbeer** 2013-05-09 00:04 UTC
